name: oogiri_taizen
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # To use Flavor
  flutter_flavor: ^2.0.0
  flutter_flavorizr: ^2.0.0

  # For Architecture
  hooks_riverpod: ^0.14.0+4
  flutter_hooks: ^0.17.0

  # To use Firebase
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  cloud_firestore: ^3.1.0
  firebase_storage: ^10.1.0
  firebase_crashlytics: ^2.3.0
  firebase_analytics: ^8.3.4
  firebase_performance: ^0.7.1+4
  firebase_dynamic_links: ^3.0.1
  firebase_messaging: ^11.1.0
  cloud_functions: ^3.1.1
  firebase_remote_config: ^0.11.0+2

  # For lint
  pedantic_mono: ^1.12.1

  # For UI
  cached_network_image: ^3.0.0
  convex_bottom_bar: ^3.0.0
  loading_overlay: ^0.3.0
  rflutter_alert: ^2.0.2
  flutter_signin_button: ^2.0.0
  package_info_plus: ^1.1.0
  photo_view: ^0.12.0
  image_picker: ^0.8.4+4
  image_cropper: ^1.4.1
  flutter_image_compress: ^1.0.0
  circular_menu: ^1.2.2
  freezed_annotation: ^0.14.2
  flutter_html: ^2.1.5

  # To Use SharedPreferences
  streaming_shared_preferences: ^2.0.0

  # For Authenticate
  google_sign_in: ^5.0.7
  sign_in_with_apple: ^3.0.0

  # To Use Tuple
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.6
  freezed: ^0.14.2
  json_serializable: ^4.1.3

  # For icon
  flutter_launcher_icons: ^0.9.2

  # For Splash Screen
  flutter_native_splash: ^1.3.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_default.jpg"
  adaptive_icon_foreground: "assets/images/icon_adaptive.jpg"
  adaptive_icon_background: "#FFCC00"

flutter_native_splash:
  image: assets/images/icon_splash_screen.png
  color: "#FFCC00"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pu b/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# Flavorの設定
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    development:
      app:
        name: "大喜利大全Dev"

      android:
        applicationId: "com.zwtin.oogiritaizen.dev"
        firebase:
          config: "firebase/development/google-services.json"

      ios:
        bundleId: "com.zwtin.oogiritaizen.dev"
        firebase:
          config: "firebase/development/GoogleService-Info.plist"

    production:
      app:
        name: "大喜利大全"

      android:
        applicationId: "com.zwtin.oogiritaizen"
        firebase:
          config: "firebase/production/google-services.json"
      ios:
        bundleId: "com.zwtin.oogiritaizen"
        firebase:
          config: "firebase/production/GoogleService-Info.plist"

  instructions:
    - assets:download
    - assets:extract
    - android:androidManifest
    - android:buildGradle
    - android:icons
    - ios:xcconfig
    - ios:buildTargets
    - ios:schema
    - ios:icons
    - ios:plist
    - google:firebase
    - assets:clean
    - ide:config