// Mocks generated by Mockito 5.2.0 from annotations
// in oogiri_taizen/test/unit/domain/entity/answer_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:oogiri_taizen/domain/entity/answer.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeDateTime_0 extends _i1.Fake implements DateTime {}

class _Fake$AnswerCopyWith_1<$Res> extends _i1.Fake
    implements _i2.$AnswerCopyWith<$Res> {}

/// A class which mocks [Answer].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnswer extends _i1.Mock implements _i2.Answer {
  MockAnswer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: '') as String);
  @override
  String get text =>
      (super.noSuchMethod(Invocation.getter(#text), returnValue: '') as String);
  @override
  int get viewedCount =>
      (super.noSuchMethod(Invocation.getter(#viewedCount), returnValue: 0)
          as int);
  @override
  bool get isLike =>
      (super.noSuchMethod(Invocation.getter(#isLike), returnValue: false)
          as bool);
  @override
  int get likedCount =>
      (super.noSuchMethod(Invocation.getter(#likedCount), returnValue: 0)
          as int);
  @override
  bool get isFavor =>
      (super.noSuchMethod(Invocation.getter(#isFavor), returnValue: false)
          as bool);
  @override
  int get favoredCount =>
      (super.noSuchMethod(Invocation.getter(#favoredCount), returnValue: 0)
          as int);
  @override
  int get popularPoint =>
      (super.noSuchMethod(Invocation.getter(#popularPoint), returnValue: 0)
          as int);
  @override
  String get topicId =>
      (super.noSuchMethod(Invocation.getter(#topicId), returnValue: '')
          as String);
  @override
  String get createdUserId =>
      (super.noSuchMethod(Invocation.getter(#createdUserId), returnValue: '')
          as String);
  @override
  DateTime get createdAt => (super.noSuchMethod(Invocation.getter(#createdAt),
      returnValue: _FakeDateTime_0()) as DateTime);
  @override
  _i2.$AnswerCopyWith<_i2.Answer> get copyWith =>
      (super.noSuchMethod(Invocation.getter(#copyWith),
              returnValue: _Fake$AnswerCopyWith_1<_i2.Answer>())
          as _i2.$AnswerCopyWith<_i2.Answer>);
}
