// Mocks generated by Mockito 5.2.0 from annotations
// in oogiri_taizen/test/unit/domain/entity/topic_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:oogiri_taizen/domain/entity/topic.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeDateTime_0 extends _i1.Fake implements DateTime {}

class _Fake$TopicCopyWith_1<$Res> extends _i1.Fake
    implements _i2.$TopicCopyWith<$Res> {}

/// A class which mocks [Topic].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopic extends _i1.Mock implements _i2.Topic {
  MockTopic() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: '') as String);
  @override
  String get text =>
      (super.noSuchMethod(Invocation.getter(#text), returnValue: '') as String);
  @override
  int get answeredCount =>
      (super.noSuchMethod(Invocation.getter(#answeredCount), returnValue: 0)
          as int);
  @override
  String get userId =>
      (super.noSuchMethod(Invocation.getter(#userId), returnValue: '')
          as String);
  @override
  DateTime get createdAt => (super.noSuchMethod(Invocation.getter(#createdAt),
      returnValue: _FakeDateTime_0()) as DateTime);
  @override
  DateTime get updatedAt => (super.noSuchMethod(Invocation.getter(#updatedAt),
      returnValue: _FakeDateTime_0()) as DateTime);
  @override
  List<_i2.TopicAnswer> get answers =>
      (super.noSuchMethod(Invocation.getter(#answers),
          returnValue: <_i2.TopicAnswer>[]) as List<_i2.TopicAnswer>);
  @override
  _i2.$TopicCopyWith<_i2.Topic> get copyWith =>
      (super.noSuchMethod(Invocation.getter(#copyWith),
              returnValue: _Fake$TopicCopyWith_1<_i2.Topic>())
          as _i2.$TopicCopyWith<_i2.Topic>);
}
