// Mocks generated by Mockito 5.2.0 from annotations
// in oogiri_taizen/test/unit/domain/entity/user_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:oogiri_taizen/domain/entity/user.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _Fake$UserCopyWith_0<$Res> extends _i1.Fake
    implements _i2.$UserCopyWith<$Res> {}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i2.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: '') as String);
  @override
  String get name =>
      (super.noSuchMethod(Invocation.getter(#name), returnValue: '') as String);
  @override
  String get introduction =>
      (super.noSuchMethod(Invocation.getter(#introduction), returnValue: '')
          as String);
  @override
  _i2.$UserCopyWith<_i2.User> get copyWith =>
      (super.noSuchMethod(Invocation.getter(#copyWith),
              returnValue: _Fake$UserCopyWith_0<_i2.User>())
          as _i2.$UserCopyWith<_i2.User>);
}
