name: app_distribution

on: 
  push:
    branches:
      - github_actions

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 20

    steps:
      - name: checkout
        uses: actions/checkout@v2

    steps:
      - name: install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
          channel: 'stable'
 
    steps:
      - name: flutter pub get
        run: flutter pub get 
